- name: Compute Engine Instance Examples
  hosts: localhost
  vars:
    ef_release_instances: ef-rel-jenkins0,ef-rel-nexus0,ef-rel-gerrit0
    
  tasks:
  
    - name: create nexus
      tags: config
      gce:
        instance_names: ef-rel-nexus0
        zone: "{{ egcp_zone }}"
        machine_type: g1-small
        image: centos-7-v20181011
        state: present
        service_account_email: "{{ service_account_email }}"
        credentials_file: "{{ credentials_file }}"
        project_id: "{{ project_id }}"
        tags: web-808x
        metadata : '{ "sshKeys":"{{gce_sshKeys}}"}'        

    - name: create jenkins-master
      tags: config
      gce:
        instance_names: ef-rel-jenkins0
        zone: "{{ egcp_zone }}"
        machine_type: g1-small
        image: centos-7-v20181011
        state: present
        service_account_email: "{{ service_account_email }}"
        credentials_file: "{{ credentials_file }}"
        project_id: "{{ project_id }}"
        tags: web-808x
        metadata : '{ "sshKeys":"{{gce_sshKeys}}"}'

    - name: create gerrit
      tags: config
      gce:
        instance_names: ef-rel-gerrit0
        zone: "{{ egcp_zone }}"
        machine_type: g1-small
        image: centos-7-v20181011
        state: present
        service_account_email: "{{ service_account_email }}"
        credentials_file: "{{ credentials_file }}"
        project_id: "{{ project_id }}"
        tags: web-808x
        metadata : '{ "sshKeys":"{{gce_sshKeys}}"}'
  
    - name: collect active instances
      tags: all
      gce:
        instance_names: "{{ ef_release_instances }}"
        zone: "{{ egcp_zone }}"
        state: active
        service_account_email: "{{ service_account_email }}"
        credentials_file: "{{ credentials_file }}"
        project_id: "{{ project_id }}"
      register: gce_rel

    - name: Save host data
      tags: all
      add_host:
        hostname: "{{ item.name }}"
        ansible_ssh_host: "{{ item.public_ip }}"
        groupname: release
        ansible_ssh_user: jagular_spb
        ansible_ssh_private_key_file: "~/.ssh/id_ef_gd"
        ansible_paramiko_host_key_checking: false
      with_items: "{{ gce_rel.instance_data }}"
  
    - name: Create FW Rule
      tags: config
      gce_net:
       credentials_file: "{{ credentials_file }}"      
       service_account_email: "{{ service_account_email }}"
       pem_file: "{{ credentials_file }}"
       project_id: "{{ project_id }}"
       name: default
       fwname: firewall0
       allowed: tcp:8080,8081
       state: present
       target_tags: web-808x

##
- name: Configure Jenkins
  tags: jenkins
  hosts: ef-rel-jenkins0
  become: yes
  become_method: sudo
  gather_facts: no  
  roles:
  - common
  - jenkins_master
  - docker

- name: Configure Gerrit
  tags: gerrit
  hosts: ef-rel-gerrit0
  become: yes
  become_method: sudo
  gather_facts: no  
  roles:
  - common
  - gerrit

- name: Configure Nexus
  tags: jenkins
  hosts: ef-rel-nexus0
  become: yes
  become_method: sudo
  gather_facts: no  
  roles:
  - common
  - nexus
