- name: Compute Engine Instance Examples
  hosts: localhost
  vars:
    ef_build_instances: ef-build-docker0,ef-build-docker1
    
  tasks:
    - name: create docker
      tags: config
      gce:
        instance_names: ef-build-docker0,ef-build-docker1
        zone: "{{ egcp_zone }}"
        machine_type: g1-small
        image: centos-7-v20181011
        state: present
        service_account_email: "{{ service_account_email }}"
        credentials_file: "{{ credentials_file }}"
        project_id: "{{ project_id }}"
        tags: web-docker
        metadata : '{ "sshKeys":"{{gce_sshKeys}}"}'
      register: gce_docker

    - name: Throttle
      wait_for_connection:
       delay: 60
       sleep: 5
       timeout: 300
      when: gce_docker.changed

    - name: collect active instances
      tags: all
      gce:
        instance_names: "{{ ef_build_instances }}"
        zone: "{{ egcp_zone }}"
        state: active
        service_account_email: "{{ service_account_email }}"
        credentials_file: "{{ credentials_file }}"
        project_id: "{{ project_id }}"
      register: gce_build

    - name: Save host data
      tags: all
      add_host:
        hostname: "{{ item.name }}"
        ansible_ssh_host: "{{ item.public_ip }}"
        groupname: build
        ansible_ssh_user: jagular_spb
        ansible_ssh_private_key_file: "~/.ssh/id_ef_gd"
        ansible_paramiko_host_key_checking: false
        private_ip: "{{item.private_ip}}"
      with_items: "{{ gce_build.instance_data }}"
##
  
- name: Configure Docker
  tags: build
  hosts: ef-build-docker0,ef-build-docker1
  become: yes
  become_method: sudo
  gather_facts: no  
  roles:
  - common
  - docker
