---
    - name: Install plugins without a specific version
      jenkins_plugin:
       url: "http://{{jenkins_url}}"
       url_password: "{{vault_jenkins_password}}"
       url_username: "{{jenkins_url_username}}"
       name: "{{ item.key }}"
      register: jenkins_plugin_unversioned
      when: >
        'version' not in item.value
      with_dict: "{{ jenkins_plugins }}"

    - name: Initiate the fact
      set_fact:
        jenkins_restart_required: no

    - name: Check if restart is required by any of the unversioned plugins
      set_fact:
        jenkins_restart_required: yes
      when: item.changed
      with_items: "{{ jenkins_plugin_unversioned.results }}"

    - name: Restart Jenkins if required
      service:
        name: jenkins
        state: restarted
      when: jenkins_restart_required

    - name: Wait for Jenkins - Get Jenkins Crumb
      uri:
       url: 'http://{{jenkins_url}}/crumbIssuer/api/xml?xpath=concat(//crumbRequestField,":",//crumb)'
       user: "{{jenkins_url_username}}"
       password: "{{jenkins_url_password}}"
       force_basic_auth: yes
       return_content: yes
       status_code: 200
       timeout: 5
      # Keep trying for 5 mins in 5 sec intervals
      retries: 60
      delay: 5
      until: >
         'status' in crumb and
         crumb['status'] == 200
      register: crumb
      when: jenkins_restart_required

    - name: Wait for Jenkins - Auth Ok?
      uri:
        password: "{{jenkins_url_password}}"
        user: "{{jenkins_url_username}}"
        url: "http://{{jenkins_url}}/api/json"
        force_basic_auth: yes
        method: POST
        headers:
         Jenkins-Crumb: "{{ crumb.content.split(':')[1] }}"
        status_code: 200
        timeout: 5
      register: jenkins_service_status
      # Keep trying for 5 mins in 5 sec intervals
      retries: 60
      delay: 5
      until: >
         'status' in jenkins_service_status and
         jenkins_service_status['status'] == 200
      when: jenkins_restart_required

    - name: Reset the fact
      set_fact:
        jenkins_restart_required: no
      when: jenkins_restart_required

    - name: Plugin enabling
      jenkins_plugin:
       url: "http://{{jenkins_url}}"
       url_password: "{{vault_jenkins_password}}"
       url_username: "{{jenkins_url_username}}"
       name: "{{ item.key }}"
       state: "{{ 'enabled' if item.value['enabled'] else 'disabled'}}"
      when: >
        'enabled' in item.value
      with_dict: "{{ jenkins_plugins }}"