---

#    - name: Swarm leave
#      docker_swarm:
#       state: absent
#       force: yes
#      when: inventory_hostname  == "ef-build-docker0"

    - name: Swarm master
      docker_swarm:
       state: present
       advertise_addr: "{{private_ip}}"
      register: swarm_master
      when: inventory_hostname  == "ef-build-docker0"

    - name:
      set_fact:
       swrmtkn: "{{swarm_master.swarm_facts.JoinTokens.Worker}}"
#      when: swarm_master.changed
      when: inventory_hostname  == "ef-build-docker0"

    - name: Swarm Master Firewalld
      firewalld:
       port: 2377/tcp
       permanent: true
       immediate: yes
       state: enabled
       
    - name: Swarm Master Jenkins
      shell: |
       echo "-master {{jenkins_swarm_url}} -password {{jenkins_swarm_password}} -username {{jenkins_swarm_username}}"| docker secret create jenkins-v1 -
       docker service create --mode=global --name jenkins-swarm-agent -e LABELS=docker-prod
       --mount "type=bind,source=/var/run/docker.sock,target=/var/run/docker.sock"
       --mount "type=bind,source=/tmp/,target=/tmp/"
       --secret source=jenkins-v1,target=jenkins
       vfarcic/jenkins-swarm-agent
       args:
        executable: /bin/bash

    - name: Wait 300 seconds for port 2377
      wait_for:
       port: 2377
       host: "{{hostvars['ef-build-docker0']['private_ip']}}"
       delay: 10
#      connection: local
      when: inventory_hostname  != "ef-build-docker0"

#    - name: Swarm add node
#      debug: 
#       msg: "{{hostvars['ef-build-docker0']['swrmtkn']}}"
#      when: inventory_hostname  != "ef-build-docker0"      

#    - name: Swarm leave
#      docker_swarm:
#       state: absent
#       force: yes
#      when: inventory_hostname  != "ef-build-docker0"
      
    - name: Swarm add node
      docker_swarm:
       state: join
       join_token: "{{hostvars['ef-build-docker0']['swrmtkn']}}"
       advertise_addr: "{{private_ip}}"
       remote_addrs: "{{hostvars['ef-build-docker0']['private_ip']}}"
      register: swarm_node
      when: inventory_hostname  != "ef-build-docker0"

