---

- name: Swarm Master Jenkins 1st
  shell: |-
   echo '-master {{jenkins_swarm_url}} -password {{jenkins_swarm_password}} -username {{jenkins_swarm_username}}' | docker secret create jenkins-v1 -
   args:
    executable: /bin/bash
  when: inventory_hostname  == "ef-build-docker0"


- name: Swarm Master Jenkins 2nd
  shell: |-
   docker service create --mode=global --name jenkins-swarm-agent -e LABELS=docker-prod
   --mount "type=bind,source=/var/run/docker.sock,target=/var/run/docker.sock"
   --mount "type=bind,source=/tmp/,target=/tmp/"
   --secret source=jenkins-v1,target=jenkins
   vfarcic/jenkins-swarm-agent
   args:
    executable: /bin/bash
  when: inventory_hostname  == "ef-build-docker0"

