---
- name: Nexus sytemd file
  copy:
   src: nexus.service
   dest: /etc/systemd/system/
      
- name: just force systemd to reread configs
  systemd: daemon_reload=yes
  
- name: Nexus run
  service:
   name: nexus
   enabled: yes
   state: started
    
