---

- name: "Add user nexus"
  user:
   name: nexus
   shell: /bin/bash
   home: /opt/nexus
   state: present
   create_home: no

#- name: Gerrit Dir
#  file:
#   dest: /var/gerrit/bin
#   owner: gerrit
#   group: gerrit
#   mode:  ug+rx,o-rwx
#   state: directory
   
- name: Nexus Dload
  get_url:
   url: "{{nexus_dl_url}}"
   dest: /tmp/
   checksum : "{{nexus_dl_sha}}"
   mode: ugo+r
  register: nexus_dl

- name: Nexus Anarhive
  unarchive:
   src: "{{nexus_dl.dest}}"
   remote_src: yes
   dest: "/opt/"
   owner: nexus
   group: nexus
  when: nexus_dl.state == 'file'

- name: Nexus symlinc
  file:
   state: link
   src: "/opt/{{nexus_ver}}"
   dest: "/opt/nexus"
   