---
- name: Gerrit sytemd file
  copy:
   src: gerrit.service
   dest: /etc/systemd/system/
      
- name: just force systemd to reread configs
  systemd: daemon_reload=yes
  
- name: Gerrit run
  service:
   name: gerrit
   enabled: yes
   state: started
    
