---

- name: Add Gerrit repo
  yum_repository:
   mirrorlist: http://mirrorlist.gerritforge.com/yum
   name: gerritforge
   state: present
   owner: root
   group: root
   mode: u+rw,g+r,o+r
   gpgcheck: yes
#   gpgkey: https://jenkins-ci.org/redhat/jenkins-ci.org.key
   enabled: no
   ip_resolve: 4
   description: GerritForge repository for Gerrit Code Review
   
- name: Install Gerrit
  yum:
   state: present
   name: gerrit-2.14.6-1.noarch
   update_cache: no
   enablerepo: gerritforge

#- name: Enable Gerrit
#  service:
#   name: gerrit
#   enabled: yes
#   state: stopped


https://gerrit-releases.storage.googleapis.com/gerrit-2.14.6.war