---
    - name: Install apache
      apt:
       state: present
       name: apache2
       update_cache: yes

    - name: Run apache
      service:
        name: apache2
        state: started
        enabled: yes

