---
    - name: Install git
      yum:
       state: present
       name: git
       update_cache: no

    - name: Install wget
      yum:
       state: present
       name: wget
       update_cache: no

    - name: Install jdk
      yum:
       state: present
       name: java-1.8.0-openjdk
       update_cache: no

    - name: set $JAVA_HOME
      copy:
       src: java_home.sh
       dest: /etc/profile.d
       mode: ugo+rx
       owner: root
       group: root

