---
   
- name: Docker configure daemon 
  copy:
   src: docker_daemon.json
   dest: /etc/docker/daemon.json
  register: configure

- name: Docker run
  service:
   name: docker
   enabled: yes
   state: restarted
  when: configure.changed