---


- name: Docker Yum
  yum:
   state: present
   name: docker
   update_cache: no

- name: Docker enabled
  service:
   name: docker
   enabled: yes
   state: started

- name: Python2 pip
  yum:
   state: present
   name: python2-pip
   update_cache: no

- name: Python2 docker
  shell: "pip install docker"
